import { constants, promises as fs } from "node:fs";
import path from "node:path";
import { canonicalJson, DAILY_DRIVER_SUITE_VERSION, sha256, validateReceipt, type DailyDriverReceiptV1, type EvidenceReference } from "./contract.js";
import { DAILY_DRIVER_RATE_CARD_VERSION } from "./rate-card.js";
import { DAILY_DRIVER_RUNTIME_POLICY_VERSION, resolveTrustedRuntime } from "./runtime-policy.js";
import { AUTHORITY_SCHEMA_VERSION, TRUSTED_EXPECTED_SCHEMA_VERSION, assertExpectedFieldsCorrespond, computeAuthorityDigest, expectedObjectDigest, type TrustedExpectedEvidence } from "./expected-authority.js";

export const EVIDENCE_MANIFEST_VERSION = "howa.hermes-daily-driver.evidence-manifest.v1" as const;
export interface EvidenceManifestEntry { path: string; byte_length: number; digest: string; evidence_class: EvidenceReference["kind"]; run_id: string; trial_id: string; }
export interface EvidenceManifest { schema_version: typeof EVIDENCE_MANIFEST_VERSION; run_id: string; trial_id: string; entries: EvidenceManifestEntry[]; }
export interface PostHocAdjudication { schema_version: "howa.ddv1-post-hoc-adjudication.v1"; run_id: string; trial_id: string; attempt: number; expected: Record<string, unknown>; candidate_submitted: Record<string, unknown> | null; comparisons: DailyDriverReceiptV1["deterministic_checks"]; consumed_expected_fields: string[]; expected_object_digest: string; authority_digest: string; validator_check_set_digest: string; raw_verdict: DailyDriverReceiptV1["raw_verdict"]; accepted: boolean; disqualifier_codes: string[]; }

function record(value: unknown, label: string): Record<string, unknown> { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be an object`); return value as Record<string, unknown>; }
function exactKeys(value: Record<string, unknown>, keys: string[], label: string): void { if (canonicalJson(Object.keys(value).sort()) !== canonicalJson([...keys].sort())) throw new Error(`${label} has unexpected or missing fields`); }
function digest(value: unknown, label: string): asserts value is string { if (typeof value !== "string" || !/^sha256:[a-f0-9]{64}$/.test(value)) throw new Error(`${label} must be a SHA-256 digest`); }
function normalized(relative: string): string { const value = relative.split(path.sep).join("/"); if (!value || path.posix.isAbsolute(value) || value.split("/").some((part) => part === "" || part === "." || part === "..")) throw new Error(`unsafe evidence path: ${relative}`); return value; }
function inside(root: string, relative: string): string { const rel = normalized(relative); const target = path.resolve(root, rel); const base = `${path.resolve(root)}${path.sep}`; if (!target.startsWith(base)) throw new Error(`evidence path escapes root: ${relative}`); return target; }
async function writeOnce(target: string, bytes: string): Promise<void> { await fs.mkdir(path.dirname(target), { recursive: true }); const handle = await fs.open(target, constants.O_CREAT | constants.O_EXCL | constants.O_WRONLY, 0o444); try { await handle.writeFile(bytes); await handle.sync(); } finally { await handle.close(); } }
export async function buildEvidenceManifest(outputRoot: string, runId: string, trialId: string, refs: EvidenceReference[]): Promise<{ manifest: EvidenceManifest; path: string; digest: string }> {
  const seen = new Set<string>(); const entries: EvidenceManifestEntry[] = [];
  for (const ref of refs) { const relative = normalized(ref.path); if (seen.has(relative)) throw new Error(`duplicate evidence path: ${relative}`); seen.add(relative); const target = inside(outputRoot, relative); const info = await fs.lstat(target); if (!info.isFile() || info.isSymbolicLink()) throw new Error(`evidence must be a regular non-symlink file: ${relative}`); const bytes = await fs.readFile(target); const entryDigest = sha256(bytes); if (entryDigest !== ref.digest) throw new Error(`evidence digest changed before manifest: ${relative}`); entries.push({ path: relative, byte_length: bytes.length, digest: entryDigest, evidence_class: ref.kind, run_id: runId, trial_id: trialId }); }
  entries.sort((a,b)=>a.path.localeCompare(b.path)); const manifest: EvidenceManifest = { schema_version: EVIDENCE_MANIFEST_VERSION, run_id: runId, trial_id: trialId, entries }; const relative = `manifests/${runId}/${trialId}.evidence-manifest.json`; const bytes = `${canonicalJson(manifest)}\n`; await writeOnce(inside(outputRoot, relative), bytes); return { manifest, path: relative, digest: sha256(bytes) };
}
async function walkFiles(root: string): Promise<string[]> { const out: string[] = []; async function walk(dir: string): Promise<void> { for (const entry of await fs.readdir(dir,{withFileTypes:true})) { const full=path.join(dir,entry.name); if(entry.isSymbolicLink()) throw new Error(`symlink in evidence scope: ${full}`); if(entry.isDirectory()) await walk(full); else if(entry.isFile()) out.push(path.relative(root,full).split(path.sep).join("/")); else throw new Error(`non-file evidence entry: ${full}`); } } await walk(root); return out.sort(); }

const TRUSTED_EXPECTED_KEYS = ["schema_version","suite_version","runtime_policy_version","run_id","trial_id","attempt","fixture_digest","entropy_commitment","expected","expected_object_digest","consumed_expected_fields","validator_check_ids","validator_check_set_digest","required_sources_digest","authority_digest"];
function verifyTrustedExpected(raw: unknown, receipt: DailyDriverReceiptV1, attempt: number): TrustedExpectedEvidence {
  const value = record(raw, "trusted expected evidence"); exactKeys(value, TRUSTED_EXPECTED_KEYS, "trusted expected evidence");
  if (value.schema_version !== TRUSTED_EXPECTED_SCHEMA_VERSION || value.suite_version !== receipt.trial_suite_version || value.runtime_policy_version !== receipt.runtime_policy_version || value.run_id !== receipt.run_id || value.trial_id !== receipt.trial_id || value.attempt !== attempt || value.fixture_digest !== receipt.fixture_digest || value.entropy_commitment !== receipt.campaign_entropy_commitment) throw new Error("trusted expected evidence identity mismatch");
  const expected = record(value.expected, "trusted expected object"); const checkSet = assertExpectedFieldsCorrespond(receipt.trial_id, expected);
  if (canonicalJson(value.consumed_expected_fields) !== canonicalJson(checkSet.consumed_expected_fields) || canonicalJson(value.validator_check_ids) !== canonicalJson(checkSet.validator_check_ids) || value.validator_check_set_digest !== checkSet.validator_check_set_digest) throw new Error("trusted expected validator check-set mismatch");
  const expectedDigest = expectedObjectDigest(expected); if (value.expected_object_digest !== expectedDigest || expectedDigest !== receipt.expected_object_digest) throw new Error("trusted expected object digest mismatch"); digest(value.required_sources_digest, "required_sources_digest");
  const authority = computeAuthorityDigest({ run_id: receipt.run_id, trial_id: receipt.trial_id, fixture_digest: receipt.fixture_digest, entropy_commitment: receipt.campaign_entropy_commitment, expected_object_digest: expectedDigest, validator_check_set_digest: checkSet.validator_check_set_digest, required_sources_digest: value.required_sources_digest });
  if (value.authority_digest !== authority || authority !== receipt.authority_digest) throw new Error("trusted expected authority digest mismatch"); return value as unknown as TrustedExpectedEvidence;
}
function parseCandidate(stdout: string): Record<string, unknown> | null { const trimmed = stdout.trim(); for (const candidate of [trimmed, ...trimmed.split(/\r?\n/).reverse()]) { if (!candidate.startsWith("{") || !candidate.endsWith("}")) continue; try { const value = record(JSON.parse(candidate), "candidate report"); return record(value.observations, "candidate observations"); } catch { /* wrapper output may precede report */ } } return null; }

async function verifyBundle(receipt: DailyDriverReceiptV1, outputRoot: string): Promise<{ expectedByAttempt: Map<number, TrustedExpectedEvidence>; finalValidator: Record<string, unknown> | null }> {
  const manifestPath = inside(outputRoot, receipt.evidence_manifest_path); const manifestInfo = await fs.lstat(manifestPath); if(!manifestInfo.isFile()||manifestInfo.isSymbolicLink()) throw new Error("evidence manifest is not a regular file"); const manifestBytes=await fs.readFile(manifestPath); if(sha256(manifestBytes)!==receipt.evidence_manifest_digest) throw new Error("evidence manifest digest mismatch"); const manifest=JSON.parse(manifestBytes.toString("utf8")) as EvidenceManifest; if(manifest.schema_version!==EVIDENCE_MANIFEST_VERSION||manifest.run_id!==receipt.run_id||manifest.trial_id!==receipt.trial_id||!Array.isArray(manifest.entries)) throw new Error("evidence manifest identity/schema mismatch");
  const expectedRefs=new Map(receipt.evidence_references.map((ref)=>[normalized(ref.path),ref])); if(expectedRefs.size!==receipt.evidence_references.length) throw new Error("duplicate receipt evidence paths"); const seen=new Set<string>(); for(const entry of manifest.entries){ const rel=normalized(entry.path); if(seen.has(rel)) throw new Error(`duplicate manifest path: ${rel}`); seen.add(rel); const ref=expectedRefs.get(rel); if(!ref||ref.digest!==entry.digest||ref.kind!==entry.evidence_class||entry.run_id!==receipt.run_id||entry.trial_id!==receipt.trial_id) throw new Error(`manifest/reference mismatch: ${rel}`); const target=inside(outputRoot,rel); const info=await fs.lstat(target); if(!info.isFile()||info.isSymbolicLink()) throw new Error(`invalid evidence file: ${rel}`); const bytes=await fs.readFile(target); if(bytes.length!==entry.byte_length||sha256(bytes)!==entry.digest) throw new Error(`evidence bytes mismatch: ${rel}`); } if(seen.size!==expectedRefs.size) throw new Error("manifest omits receipt evidence");
  const artifactRoot=inside(outputRoot,`artifacts/${receipt.run_id}/${receipt.trial_id}`); const actual=(await walkFiles(artifactRoot)).map((rel)=>`artifacts/${receipt.run_id}/${receipt.trial_id}/${rel}`); const declared=[...seen].filter((rel)=>rel.startsWith(`artifacts/${receipt.run_id}/${receipt.trial_id}/`)).sort(); if(canonicalJson(actual)!==canonicalJson(declared)) throw new Error("evidence directory contains missing, extra, or renamed files");
  const trustedRefs = receipt.evidence_references.filter((ref) => ref.kind === "trusted_expected" && /attempt-(\d+)\.trusted-expected\.json$/.test(ref.path)); if (trustedRefs.length !== receipt.attempts.length) throw new Error("exactly one trusted expected artifact is required for every attempt"); const expectedByAttempt = new Map<number, TrustedExpectedEvidence>();
  for (const ref of trustedRefs) { const match = /attempt-(\d+)\.trusted-expected\.json$/.exec(ref.path)!; const attempt = Number(match[1]); const expectedPath = `artifacts/${receipt.run_id}/${receipt.trial_id}/attempt-${attempt}.trusted-expected.json`; if (ref.path !== expectedPath || expectedByAttempt.has(attempt) || !receipt.attempts.some((item) => item.attempt === attempt)) throw new Error("trusted expected artifact path/attempt mismatch"); expectedByAttempt.set(attempt, verifyTrustedExpected(JSON.parse(await fs.readFile(inside(outputRoot, ref.path), "utf8")), receipt, attempt)); }
  if (canonicalJson([...expectedByAttempt.keys()].sort((a,b)=>a-b)) !== canonicalJson(receipt.attempts.map((item)=>item.attempt).sort((a,b)=>a-b))) throw new Error("trusted expected evidence attempt coverage mismatch"); const expectedCanonical = new Set([...expectedByAttempt.values()].map((value)=>canonicalJson(value.expected))); if(expectedCanonical.size!==1) throw new Error("trusted expected values changed across retries");
  const authorityRef=receipt.evidence_references.find((ref)=>ref.path===`artifacts/${receipt.run_id}/${receipt.trial_id}/trusted-authority.json`); if(!authorityRef) throw new Error("trusted campaign authority evidence missing"); const authority=record(JSON.parse(await fs.readFile(inside(outputRoot,authorityRef.path),"utf8")),"trusted campaign authority"); const authorityKeys=["schema_version","suite_version","runtime_policy_version","run_id","trial_id","entropy_commitment","fixture_digest","expected_object_digest","validator_check_set_digest","required_sources_digest","authority_digest"]; exactKeys(authority,authorityKeys,"trusted campaign authority"); const first=[...expectedByAttempt.values()][0]!; if(authority.schema_version!==AUTHORITY_SCHEMA_VERSION||authority.suite_version!==DAILY_DRIVER_SUITE_VERSION||authority.runtime_policy_version!==DAILY_DRIVER_RUNTIME_POLICY_VERSION||authority.run_id!==receipt.run_id||authority.trial_id!==receipt.trial_id||authority.fixture_digest!==receipt.fixture_digest||authority.entropy_commitment!==receipt.campaign_entropy_commitment||authority.expected_object_digest!==receipt.expected_object_digest||authority.validator_check_set_digest!==receipt.validator_check_set_digest||authority.required_sources_digest!==first.required_sources_digest||authority.authority_digest!==receipt.authority_digest) throw new Error("trusted campaign authority mismatch");
  const validatorRefs=receipt.evidence_references.filter((ref)=>/attempt-(\d+)\.validator\.json$/.test(ref.path)); let finalValidator: Record<string,unknown>|null=null;
  for(const ref of validatorRefs){const value=record(JSON.parse(await fs.readFile(inside(outputRoot,ref.path),"utf8")),"validator evidence");const match=/attempt-(\d+)\.validator\.json$/.exec(ref.path)!;const attempt=Number(match[1]);const expected=expectedByAttempt.get(attempt);if(!expected)throw new Error("validator has no corresponding trusted expected evidence"); exactKeys(value,["schema_version","run_id","trial_id","attempt","fixture_digest","entropy_commitment","expected_object_digest","authority_digest","validator_check_set_digest","consumed_expected_fields","validator_check_ids","checks","raw_verdict","accepted","disqualifier_codes"],"validator evidence"); if(value.schema_version!=="howa.ddv1-validator-result.v2"||value.run_id!==receipt.run_id||value.trial_id!==receipt.trial_id||value.attempt!==attempt||value.fixture_digest!==receipt.fixture_digest||value.entropy_commitment!==receipt.campaign_entropy_commitment||value.expected_object_digest!==expected.expected_object_digest||value.authority_digest!==expected.authority_digest||value.validator_check_set_digest!==expected.validator_check_set_digest||canonicalJson(value.consumed_expected_fields)!==canonicalJson(expected.consumed_expected_fields)||canonicalJson(value.validator_check_ids)!==canonicalJson(expected.validator_check_ids)) throw new Error("validator/expected correspondence mismatch"); const checks=Array.isArray(value.checks)?value.checks:[];const correspondence=checks.find((item)=>record(item,"validator check").id==="authority.expected-correspondence") as Record<string,unknown>|undefined;if(!correspondence||correspondence.passed!==true||!Array.isArray(correspondence.evidence_refs)||!correspondence.evidence_refs.includes(`attempt-${attempt}.trusted-expected.json`))throw new Error("validator did not consume the bound trusted expected artifact"); finalValidator=value; }
  if(finalValidator&&canonicalJson(finalValidator.checks)!==canonicalJson(receipt.deterministic_checks))throw new Error("receipt deterministic checks differ from retained validator result"); return {expectedByAttempt,finalValidator};
}

export async function verifyReceiptEvidence(receipt: DailyDriverReceiptV1, outputRoot: string, verifyLocalRuntime = true): Promise<void> { validateReceipt(receipt); const { expectedByAttempt } = await verifyBundle(receipt, outputRoot); const identityRef=receipt.evidence_references.find((ref)=>ref.path.endsWith("runtime-identity.json")); if(!identityRef) throw new Error("runtime identity evidence missing"); const identity=record(JSON.parse(await fs.readFile(inside(outputRoot,identityRef.path),"utf8")),"runtime identity evidence"); for(const key of ["hermes_launcher_digest","terminal_sandbox_digest","hermes_executable_digest","runtime_policy_version","runtime_policy_digest","hermes_configuration_digest","system_prompt_digest","tool_registry_digest","cost_rate_card_version","campaign_entropy_commitment"] as const) if(identity[key]!==receipt[key]) throw new Error(`runtime identity mismatch: ${key}`); if(receipt.runtime_policy_version!==DAILY_DRIVER_RUNTIME_POLICY_VERSION||receipt.cost_rate_card_version!==DAILY_DRIVER_RATE_CARD_VERSION||receipt.trial_suite_version!==DAILY_DRIVER_SUITE_VERSION) throw new Error("unsupported frozen suite, policy, or rate card"); if(expectedByAttempt.size!==receipt.attempts.length)throw new Error("trusted expected evidence is incomplete"); if(verifyLocalRuntime){ const actualRuntime=await resolveTrustedRuntime(receipt.provider_id); if(actualRuntime.launcher_digest!==receipt.hermes_launcher_digest||actualRuntime.terminal_sandbox_digest!==receipt.terminal_sandbox_digest||actualRuntime.hermes_executable_digest!==receipt.hermes_executable_digest||actualRuntime.policy_digest!==receipt.runtime_policy_digest) throw new Error("installed trusted runtime bytes do not match receipt"); } }

export async function adjudicateReceiptEvidence(receipt: DailyDriverReceiptV1, outputRoot: string, verifyLocalRuntime = true): Promise<PostHocAdjudication> { await verifyReceiptEvidence(receipt,outputRoot,verifyLocalRuntime);const {expectedByAttempt,finalValidator}=await verifyBundle(receipt,outputRoot); if(!finalValidator)throw new Error("post-hoc adjudication requires retained validator evidence");const attempt=Number(finalValidator.attempt);const expected=expectedByAttempt.get(attempt)!; const stdoutRef=receipt.evidence_references.find((ref)=>ref.path===`artifacts/${receipt.run_id}/${receipt.trial_id}/attempt-${attempt}.stdout.txt`);if(!stdoutRef)throw new Error("candidate stdout evidence missing"); return {schema_version:"howa.ddv1-post-hoc-adjudication.v1",run_id:receipt.run_id,trial_id:receipt.trial_id,attempt,expected:expected.expected,candidate_submitted:parseCandidate(await fs.readFile(inside(outputRoot,stdoutRef.path),"utf8")),comparisons:finalValidator.checks as DailyDriverReceiptV1["deterministic_checks"],consumed_expected_fields:expected.consumed_expected_fields,expected_object_digest:expected.expected_object_digest,authority_digest:expected.authority_digest,validator_check_set_digest:expected.validator_check_set_digest,raw_verdict:receipt.raw_verdict,accepted:receipt.accepted,disqualifier_codes:receipt.disqualifier_codes}; }
