import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createAuthoritativeFixture, createCampaignEntropy } from "@howa/daily-driver/fixtures.js";
import { runDailyDriverSuite, runDailyDriverTrial, type DailyDriverCandidate } from "@howa/daily-driver/runner.js";
import { findSecrets, redact } from "@howa/velum/redaction.js";
import { canonicalJson, computeReceiptDigest, sha256 } from "@howa/daily-driver/contract.js";
import { verifyReceiptEvidence } from "@howa/daily-driver/evidence.js";
import { cleanupOwnedDailyDriverTemps, ownedDailyDriverTemp } from "./helpers/daily-driver-temp.js";

const base:DailyDriverCandidate={model_id:"offline/mock-v2",provider_id:"offline",provider_route:"direct",reasoning_level:"test",hermes_args:[],hermes_configuration:{toolsets:["terminal"]},max_attempts:1};
const temp=ownedDailyDriverTemp; afterEach(cleanupOwnedDailyDriverTemps);

describe("Daily Driver hostile trust boundaries",()=>{
  it("uses unpredictable campaign entropy while preserving retry fixture semantics",async()=>{const a=createCampaignEntropy("campaign-a"),b=createCampaignEntropy("campaign-b");const ar=await temp("entropy-a"),br=await temp("entropy-b");const a1=await createAuthoritativeFixture(path.join(ar,"one"),"ddv1-02-repository-count",a);const a2=await createAuthoritativeFixture(path.join(ar,"two"),"ddv1-02-repository-count",a);const b1=await createAuthoritativeFixture(path.join(br,"one"),"ddv1-02-repository-count",b);expect(a1.snapshot.digest).toBe(a2.snapshot.digest);expect(a1.authority.authority_digest).toBe(a2.authority.authority_digest);expect(a1.snapshot.digest).not.toBe(b1.snapshot.digest);expect(a.commitment).not.toBe(b.commitment);});
  it("defeats the public static answer-key candidate even when it makes cheap token tool touches",async()=>{const output=await temp("static");const results=await runDailyDriverSuite({candidate:{...base,model_id:"offline/static-key-v1"},output_root:output,run_id:"static-hostile"});expect(results).toHaveLength(12);expect(results.every(x=>!x.receipt.accepted)).toBe(true);expect(results.every(x=>x.receipt.tool_calls.length>0)).toBe(true);},120_000);
  it("allows Git/SHA-256 identifiers but redacts confirmed credentials contextually",async()=>{expect(findSecrets("0123456789abcdef0123456789abcdef01234567")).toHaveLength(0);expect(findSecrets("sha256:"+"a".repeat(64))).toHaveLength(0);for(const value of ["sk-ant-"+"A".repeat(32),"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0LXVzZXIifQ.signature-value-here","Authorization: Bearer token-value-1234567890",'{"access_token":"credential-value-123456"}',"-----BEGIN OPENSSH PRIVATE KEY-----\nQUJDREVGR0g=\n-----END OPENSSH PRIVATE KEY-----"]){const found=findSecrets(value);expect(found.some(x=>x.classification==="confirmed_secret")).toBe(true);expect(redact(value).redacted).not.toContain(value);}});
  it("disqualifies secrets in stdout, stderr, and tool state but permits technical hashes",async()=>{const root=await temp("redaction");const secret=await runDailyDriverTrial({candidate:{...base,model_id:"offline/secret-v1"},output_root:root,run_id:"secret"},"ddv1-07-unsupported-complete");expect(secret.receipt.disqualifier_codes).toContain("SECRET_EXPOSURE");for(const source of ["attempt-1.stdout","attempt-1.stderr","attempt-1.tool-state"]){expect(secret.receipt.redaction_events.some(x=>x.classification==="confirmed_secret"&&x.source===source)).toBe(true);}for(const ref of secret.receipt.evidence_references){const bytes=await fs.readFile(path.join(root,ref.path));expect(ref.digest).toBe(sha256(bytes));expect(bytes.toString("utf8")).not.toContain("SyntheticCredential");}const hashes=await runDailyDriverTrial({candidate:{...base,model_id:"offline/hash-v1"},output_root:root,run_id:"hash"},"ddv1-07-unsupported-complete");expect(hashes.receipt.disqualifier_codes).not.toContain("SECRET_EXPOSURE");expect(hashes.receipt.accepted).toBe(true);});
  it("rejects evidence edit, deletion, insertion, swapping, traversal, symlink, duplicate, and manifest substitution",async()=>{const source=await temp("tamper-source");const a=await runDailyDriverTrial({candidate:base,output_root:source,run_id:"tamper-a"},"ddv1-01-porcelain-parser");const b=await runDailyDriverTrial({candidate:base,output_root:source,run_id:"tamper-b"},"ddv1-02-repository-count");await verifyReceiptEvidence(a.receipt,source,true);const stdout=a.receipt.evidence_references.find(x=>x.kind==="stdout")!;const variants=await Promise.all(Array.from({length:8},async(_,i)=>{const root=await temp(`tamper-${i}`);await fs.cp(source,root,{recursive:true});return root;}));
    await fs.chmod(path.join(variants[0]!,stdout.path),0o644);await fs.appendFile(path.join(variants[0]!,stdout.path),"changed");await expect(verifyReceiptEvidence(a.receipt,variants[0]!,false)).rejects.toThrow(/evidence bytes mismatch/);
    await fs.unlink(path.join(variants[1]!,stdout.path));await expect(verifyReceiptEvidence(a.receipt,variants[1]!,false)).rejects.toThrow();
    await fs.writeFile(path.join(variants[2]!,path.dirname(stdout.path),"inserted.txt"),"extra");await expect(verifyReceiptEvidence(a.receipt,variants[2]!,false)).rejects.toThrow(/extra/);
    const bstdout=b.receipt.evidence_references.find(x=>x.kind==="stdout")!;await fs.chmod(path.join(variants[3]!,stdout.path),0o644);await fs.writeFile(path.join(variants[3]!,stdout.path),await fs.readFile(path.join(source,bstdout.path)));await expect(verifyReceiptEvidence(a.receipt,variants[3]!,false)).rejects.toThrow();
    await fs.unlink(path.join(variants[4]!,stdout.path));await fs.symlink("/etc/passwd",path.join(variants[4]!,stdout.path));await expect(verifyReceiptEvidence(a.receipt,variants[4]!,false)).rejects.toThrow(/symlink|invalid evidence/);
    const rewrite=async(root:string,mutate:(manifest:any)=>void)=>{const target=path.join(root,a.receipt.evidence_manifest_path);const manifest=JSON.parse(await fs.readFile(target,"utf8"));mutate(manifest);const bytes=`${canonicalJson(manifest)}\n`;await fs.chmod(target,0o644);await fs.writeFile(target,bytes);const receipt={...a.receipt,evidence_manifest_digest:sha256(bytes)};receipt.receipt_digest=computeReceiptDigest(receipt);return receipt;};
    const traversal=await rewrite(variants[5]!,m=>{m.entries[0].path="../escape";});await expect(verifyReceiptEvidence(traversal,variants[5]!,false)).rejects.toThrow(/unsafe evidence path/);
    const duplicate=await rewrite(variants[6]!,m=>{m.entries.push({...m.entries[0]});});await expect(verifyReceiptEvidence(duplicate,variants[6]!,false)).rejects.toThrow(/duplicate manifest path/);
    const bmanifest=await fs.readFile(path.join(source,b.receipt.evidence_manifest_path));const target=path.join(variants[7]!,a.receipt.evidence_manifest_path);await fs.chmod(target,0o644);await fs.writeFile(target,bmanifest);await expect(verifyReceiptEvidence(a.receipt,variants[7]!,false)).rejects.toThrow(/manifest digest mismatch/);
  });
  it("air-gapped terminal telemetry proves fixture access and cannot see capture, homes, or credentials",async()=>{const root=await temp("forge");const result=await runDailyDriverTrial({candidate:{...base,model_id:"offline/forge-v1"},output_root:root,run_id:"forge"},"ddv1-07-unsupported-complete");expect(result.receipt.accepted).toBe(true);expect(result.receipt.tool_calls.length).toBeGreaterThan(0);expect(result.receipt.hermes_launcher_digest).not.toBe(result.receipt.terminal_sandbox_digest);});
  it("terminates an ignored-SIGTERM nested process tree, retains partial streams, and leaves no child",async()=>{const root=await temp("timeout");const result=await runDailyDriverTrial({candidate:{...base,model_id:"offline/timeout-v1"},output_root:root,run_id:"timeout",timeout_override_ms:500},"ddv1-07-unsupported-complete");expect(result.receipt.attempts[0]?.outcome).toBe("timeout");expect(result.receipt.attempts[0]?.signals_sent).toContain("SIGTERM");expect(result.receipt.timeout_events).toHaveLength(1);const stdout=result.receipt.evidence_references.find(x=>x.kind==="stdout")!,stderr=result.receipt.evidence_references.find(x=>x.kind==="stderr")!;expect(await fs.readFile(path.join(root,stdout.path),"utf8")).toContain("partial stdout retained");expect(await fs.readFile(path.join(root,stderr.path),"utf8")).toContain("partial stderr retained");await new Promise(resolve=>setTimeout(resolve,100));const survivors:string[]=[];for(const entry of await fs.readdir("/proc")){if(!/^\d+$/.test(entry))continue;try{const cmd=(await fs.readFile(`/proc/${entry}/cmdline`,"utf8")).replaceAll("\0"," ");if(cmd.includes("howa-ddv1-timeout-descendant-marker"))survivors.push(entry);}catch{}}expect(survivors).toEqual([]);await expect(verifyReceiptEvidence(result.receipt,root,true)).resolves.toBeUndefined();},30_000);
});
